server:
  port: 8000

spring:
  config:
    import: "optional:configserver:http://10.0.16.245:8888/"
  cloud:
    config:
      name: apigateway-service
      profile: config

token:
  secret: GachonUniversity2023KAKAO2023ENTERPRISE2023ACADEMY2023VER02TheBestTeam600END2023FORRELEASENOTESYSTEM2023BATTONPROJECT97X19VACATIONLETSGO
  access-expiration-time: 1800000
  refresh-expiration-time: 18000000