server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: config
  config:
    import: "optional:configserver:http://localhost:8888/"

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"