server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    active: config
  config:
    import: "optional:configserver:http://10.0.16.245:8888/"

management:
  endpoints:
    web:
      exposure:
        include: "*"