server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.16.245:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

token:
  secret: GachonUniversity2023KAKAO2023ENTERPRISE2023ACADEMY2023VER02TheBestTeam600END2023FORRELEASENOTESYSTEM2023BATTONPROJECT97X19VACATIONLETSGO
  access-expiration-time: 1800000
  refresh-expiration-time: 18000000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://10.0.19.219:8081
          predicates:
            - Path=/api/auth/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: member-service
          uri: http://10.0.19.219:8081
          predicates:
            - Path=/api/auth/email
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: member-service
          uri: http://10.0.19.219:8081
          predicates:
            - Path=/api/auth/email/check
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: member-service
          uri: http://10.0.19.219:8081
          predicates:
            - Path=/api/auth/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: member-service
          uri: http://10.0.19.219:8081
          predicates:
            - Path=/api/members/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: project-service
          uri: http://10.0.18.110:8082
          predicates:
            - Path=/api/projects/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: project-service
          uri: http://10.0.18.110:8082
          predicates:
            - Path=/api/belongs/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: project-service
          uri: http://10.0.18.110:8082
          predicates:
            - Path=/api/issues/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: project-service
          uri: http://10.0.18.110:8082
          predicates:
            - Path=/api/reports/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: project-service
          uri: http://10.0.18.110:8082
          predicates:
            - Path=/api/releases/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: notice-service
          uri: http://10.0.19.48:8083
          predicates:
            - Path=/api/notices/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
##################################################################  prometheus
        - id: member-service
          uri: http://10.0.19.219:8081
          predicates:
            - Path=/member-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: project-service
          uri: http://10.0.18.110:8082
          predicates:
            - Path=/project-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: notice-service
          uri: http://10.0.19.48:8083
          predicates:
            - Path=/notice-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"